[project]
name = "auto-chaldea"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Takamiya-reborn", email = "2196733767@qq.com" }
]
requires-python = ">=3.13"
dependencies = [
    "opencv-contrib-python>=5.0.0.93",
]

[project.scripts]
auto-chaldea = "auto_chaldea:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
